config/routes.rb
Rails.application.routes.draw do

  root "restaurants#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, shallow: true do
    resources :reviews do
      resources :endorsements
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/endorsement.rb
class Endorsement < ApplicationRecord
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy

  validates :name, length: { minimum: 3 }, uniqueness: true

  def build_review(attributes = {}, user)
    review = reviews.build(attributes)
    review.user = user
    review
  end

  # def build_restaurant(attributes = {})
  #   restaurant = restaurants.build(attributes)
  #   restaurant
  # end

  def average_rating
    return "N/A" if reviews.none?
    # reviews.inject(0) {|memo, review| memo + review.rating} / reviews.count
    reviews.average(:rating)
  end

end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, inclusion: (1..5)
  validates :thoughts,
             :presence => true,
             :length => { :minimum => 3, :message => "Must be at least 3 characters"}
  belongs_to :restaurant
  belongs_to :user
  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }
  has_many :endorsements 
end

app/models/user.rb
class User < ApplicationRecord

  has_many :restaurants
  has_many :reviews
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension
  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

  def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    render json: {new_endorsement_count: @review.endorsements.count}
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @user = User.find(current_user.id)
    @restaurant = @user.restaurants.build(restaurant_params)
    if @restaurant.save
      redirect_to(restaurants_path)
    else
      render('new')
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = Review.where("restaurant_id = #{@restaurant.id}")
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end
  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :user_id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find params[:restaurant_id]
    @review = @restaurant.build_review review_params, current_user
    if @review.save
      redirect_to restaurants_path
    else
      if @review.errors[:user]
        redirect_to restaurants_path, alert: 'You have already reviewed this restaurant'
      else
        render :new
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:thoughts, :rating, :restaurant_id, :user_id)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    stars = rating.round
    ('★' * stars) + ('☆' * (5-stars))
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YelpClone</title>
    <%= csrf_meta_tags %>
    <meta charset="UTF-8">  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">
          <p>YelpClone</p>
        </a>
      </div>
      <p><%= notice %><p>
      <p><%= alert %></p>
      <% if user_signed_in? %>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete%>
      <% else %>
        <%= link_to "Sign in", new_user_session_path %>
        <%= link_to "Sign up", new_user_registration_path %>
        <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
      <% end %>
    </nav>
    <div class = 'container-fluid'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/delete.html.haml
= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.label :description
  = f.text_area :description
  = f.submit

app/views/restaurants/edit.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.haml
= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.label :description
  = f.text_area :description
  = f.submit

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
  <% @restaurants.each do |restaurant| %>
  <h4><%= link_to restaurant.name, restaurant_path(restaurant) %></h4>
  <p><%= restaurant.description %></p>
  <% if current_user.id == restaurant.user_id %>
    <h4><%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %></h4>
    <h4><%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %></h4>
  <% end %>
  <h4><%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %></h4>
    <p>
    <% if restaurant.reviews.any? %>
       <% restaurant.reviews.each do |review| %>
         <p><%= review.thoughts %></p>
         <p><%= review.rating %></p>
         <% if current_user.id == review.user_id %>
           <!-- <h4><%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %></h4> -->
           <h4><%= link_to "Delete Review", restaurant_review_path(review.restaurant.id, review.id), method: :delete %></h4>
         <% end %>
       <% end %>
    <% end %>
    </p>
  <% end %>
<% else %>
  <h1>No restaurants yet</h1>
<% end %>

<a href="restaurants/new">Add a restaurant</a>

app/views/restaurants/index.html.haml
- if @restaurants.any?
  - @restaurants.each do |restaurant|
    %div.transparent-box
      %h3= link_to restaurant.name, restaurant_path(restaurant)
      = link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)
      = link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete
- else
  %h1 No restaurants yet!
%p
  %a(href='/restaurants/new') Add a restaurant

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <section id="errors" >
    <h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

app/views/restaurants/new.html.haml
- if @restaurant.errors.any?
  %section#errors
    %h2
      = pluralize @restaurant.errors.count, "error"
      prohibited this restaurant from being saved:
    %ul
      - @restaurant.errors.full_messages.each do |message|
        %li= message

= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.label :description
  = f.text_area :description
  = f.submit

app/views/restaurants/show.html.erb
<p><%= @restaurant.name %></p>
<p><%= @restaurant.description %></p>

app/views/restaurants/show.html.haml
%div.transparent-box
  %div.restaurant_detail
    %h1= @restaurant.name
    %p= @restaurant.description
    %span Average rating:
    %span.badge= star_rating(@restaurant.average_rating.to_i)

  %div.review_detail
    -if current_user == nil
      %p You must sign in to review
    -elsif current_user.has_reviewed?(@restaurant)
      %p You have already reviewed this restaurant
    -else
      = link_to "Write a Review", new_restaurant_review_path(@restaurant)

    %p= @restaurant.rating
    - @reviews.each do |review|
      %ul
        %li
        =review.thoughts
        %span.badge{:class => ("data-no-turbolink" if request.post?)}
        =star_rating(review.rating)
        = link_to "Endorse", review_endorsements_path(review),  class: 'endorsements-link'
        %span.endorsements_count= review.endorsements.count
        = 'endorsement'.pluralize review.endorsements.count

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %>
  <%= f.submit 'Leave Review' %>
<% end %>

app/views/reviews/new.html.haml
= form_for [@restaurant, @review] do |f|
  = f.label :Review
  = f.text_area :thoughts
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit